name: Check GCP action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2.1.3'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/533005722052/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider'
          service_account: 'iam-lab-7-target@gcp-labs-mvcp2ig8.iam.gserviceaccount.com'
          activate_credentials_file: true
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud config set project gcp-labs-mvcp2ig8
        gcloud config set account 'iam-lab-7-target@gcp-labs-mvcp2ig8.iam.gserviceaccount.comm'
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth list
        gcloud secrets list
        gcloud secrets versions list flag_iam_lab_7
        gcloud secrets versions access 1 --secret="flag_iam_lab_7"
